name: Provision Infrastructure

on:
  pull_request:
    branches:
      - main
      - prod

  push:
    branches:
      - main
      - prod

env:
  AWS_DEFAULT_REGION_DEV: us-east-1
  AWS_DEFAULT_REGION_PROD: us-west-2
  TERRAFORM_VERSION: 1.5.4

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

     - name: 'Terraform Initialize'
       run: |
         cd Yuriy  # Change this to the actual directory name
         terraform init
       continue-on-error: true

      - name: Terraform workspace
        run: |
          terraform workspace list
          terraform workspace select default
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false 
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
