name: My-githib-actions

on: 
  push:
    branches:
      - master
      
      
jobs: 
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message
      run : echo "Hello world from testing job"
      
  my_deploy:
    runs-on: ubuntu-latest
    
    steps: 
    - name: print hello message
      run: echo "Hello world from Deploy Job"
